import { useState, useEffect, useCallback } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

export type ESP32Device = {
  id: string;
  user_id: string;
  device_name: string;
  device_type: string;
  ip_address: string | null;
  api_key: string;
  is_online: boolean;
  last_seen: string | null;
  created_at: string;
};

export type SensorReading = {
  id: string;
  device_id: string;
  sensor_type: string;
  value: number;
  unit: string;
  created_at: string;
};

export const useDevices = () => {
  const { user } = useAuth();
  return useQuery({
    queryKey: ["esp32_devices", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("esp32_devices")
        .select("*")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data as ESP32Device[];
    },
    enabled: !!user,
  });
};

export const useAddDevice = () => {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (device: { device_name: string; device_type: string; ip_address?: string }) => {
      const { data, error } = await supabase
        .from("esp32_devices")
        .insert({ ...device, user_id: user!.id })
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["esp32_devices"] });
      toast.success("Device added");
    },
    onError: (e) => toast.error(e.message),
  });
};

export const useDeleteDevice = () => {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from("esp32_devices").delete().eq("id", id);
      if (error) throw error;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["esp32_devices"] });
      toast.success("Device removed");
    },
    onError: (e) => toast.error(e.message),
  });
};

export const useSensorReadings = (deviceId?: string) => {
  return useQuery({
    queryKey: ["sensor_readings", deviceId],
    queryFn: async () => {
      let query = supabase
        .from("esp32_sensor_readings")
        .select("*")
        .order("created_at", { ascending: false })
        .limit(100);
      if (deviceId) query = query.eq("device_id", deviceId);
      const { data, error } = await query;
      if (error) throw error;
      return data as SensorReading[];
    },
    enabled: !!deviceId,
    refetchInterval: 5000,
  });
};

export const useRealtimeSensorReadings = (deviceId?: string) => {
  const qc = useQueryClient();

  useEffect(() => {
    if (!deviceId) return;

    const channel = supabase
      .channel(`sensor-${deviceId}`)
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table: "esp32_sensor_readings",
          filter: `device_id=eq.${deviceId}`,
        },
        () => {
          qc.invalidateQueries({ queryKey: ["sensor_readings", deviceId] });
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [deviceId, qc]);
};

// ESP32 Arduino code generator
export const generateESP32Code = (device: ESP32Device, supabaseUrl: string, supabaseAnonKey: string) => {
  return `
// ============================================
// ESP32 Code for: ${device.device_name}
// Device Type: ${device.device_type}
// Generated by agriCultur
// ============================================

#include <WiFi.h>
#include <HTTPClient.h>
#include <ArduinoJson.h>

// WiFi credentials
const char* ssid = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";

// Supabase config
const char* supabaseUrl = "${supabaseUrl}";
const char* supabaseKey = "${supabaseAnonKey}";
const char* deviceId = "${device.id}";

// Sensor pins (adjust for your setup)
${device.device_type === "crop_rover" ? `
#define SOIL_MOISTURE_PIN 34
#define DHT_PIN 4
#define LIGHT_SENSOR_PIN 35
#define PH_SENSOR_PIN 32
` : `
#define TEMP_SENSOR_PIN 34
#define HUMIDITY_SENSOR_PIN 35
#define WEIGHT_SENSOR_PIN 32
`}

void setup() {
  Serial.begin(115200);
  WiFi.begin(ssid, password);
  
  while (WiFi.status() != WL_CONNECTED) {
    delay(1000);
    Serial.println("Connecting to WiFi...");
  }
  Serial.println("Connected!");
  Serial.print("IP: ");
  Serial.println(WiFi.localIP());
}

void sendReading(const char* sensorType, float value, const char* unit) {
  if (WiFi.status() != WL_CONNECTED) return;
  
  HTTPClient http;
  String url = String(supabaseUrl) + "/rest/v1/esp32_sensor_readings";
  
  http.begin(url);
  http.addHeader("Content-Type", "application/json");
  http.addHeader("apikey", supabaseKey);
  http.addHeader("Authorization", String("Bearer ") + supabaseKey);
  http.addHeader("Prefer", "return=minimal");
  
  StaticJsonDocument<256> doc;
  doc["device_id"] = deviceId;
  doc["sensor_type"] = sensorType;
  doc["value"] = value;
  doc["unit"] = unit;
  
  String body;
  serializeJson(doc, body);
  
  int code = http.POST(body);
  if (code > 0) {
    Serial.printf("Sent %s: %.2f %s (HTTP %d)\\n", sensorType, value, unit, code);
  } else {
    Serial.printf("Error sending %s: %s\\n", sensorType, http.errorToString(code).c_str());
  }
  http.end();
}

void loop() {
${device.device_type === "crop_rover" ? `
  // Read sensors
  float soilMoisture = analogRead(SOIL_MOISTURE_PIN) / 40.95; // 0-100%
  float lightIntensity = analogRead(LIGHT_SENSOR_PIN) / 4.095; // 0-1000 lux approx
  float soilPH = (analogRead(PH_SENSOR_PIN) / 4095.0) * 14.0; // 0-14 pH
  
  // Send readings
  sendReading("soil_moisture", soilMoisture, "%");
  sendReading("light_intensity", lightIntensity, "lux");
  sendReading("soil_ph", soilPH, "pH");
  
  // Add DHT sensor readings (temperature & humidity)
  // Requires DHT library
  // sendReading("temperature", temperature, "°C");
  // sendReading("humidity", humidity, "%");
` : `
  // Read storage sensors
  float temperature = analogRead(TEMP_SENSOR_PIN) / 40.95 * 0.5; // Scale to reasonable range
  float humidity = analogRead(HUMIDITY_SENSOR_PIN) / 40.95;
  float weight = analogRead(WEIGHT_SENSOR_PIN) / 4.095; // kg approx
  
  sendReading("temperature", temperature, "°C");
  sendReading("humidity", humidity, "%");
  sendReading("weight", weight, "kg");
`}
  
  delay(30000); // Send every 30 seconds
}
`.trim();
};
