import { useState, useEffect, useCallback } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

export type ESP32Device = {
  id: string;
  user_id: string;
  device_name: string;
  device_type: string;
  ip_address: string | null;
  api_key: string;
  is_online: boolean;
  last_seen: string | null;
  created_at: string;
};

export type SensorReading = {
  id: string;
  device_id: string;
  sensor_type: string;
  value: number;
  unit: string;
  created_at: string;
};

export const useDevices = () => {
  const { user } = useAuth();
  return useQuery({
    queryKey: ["esp32_devices", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("esp32_devices")
        .select("*")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data as ESP32Device[];
    },
    enabled: !!user,
    refetchInterval: 5000,
  });
};

export const useAddDevice = () => {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (device: { device_name: string; device_type: string; ip_address?: string }) => {
      const { data, error } = await supabase
        .from("esp32_devices")
        .insert({ ...device, user_id: user!.id })
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["esp32_devices"] });
      toast.success("Device added");
    },
    onError: (e) => toast.error(e.message),
  });
};

export const useDeleteDevice = () => {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from("esp32_devices").delete().eq("id", id);
      if (error) throw error;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["esp32_devices"] });
      toast.success("Device removed");
    },
    onError: (e) => toast.error(e.message),
  });
};

export const useSensorReadings = (deviceId?: string) => {
  return useQuery({
    queryKey: ["sensor_readings", deviceId],
    queryFn: async () => {
      let query = supabase
        .from("esp32_sensor_readings")
        .select("*")
        .order("created_at", { ascending: false })
        .limit(100);
      if (deviceId) query = query.eq("device_id", deviceId);
      const { data, error } = await query;
      if (error) throw error;
      return data as SensorReading[];
    },
    enabled: !!deviceId,
    refetchInterval: 5000,
  });
};

export const useRealtimeSensorReadings = (deviceId?: string) => {
  const qc = useQueryClient();

  useEffect(() => {
    if (!deviceId) return;

    const channel = supabase
      .channel(`sensor-${deviceId}`)
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table: "esp32_sensor_readings",
          filter: `device_id=eq.${deviceId}`,
        },
        () => {
          qc.invalidateQueries({ queryKey: ["sensor_readings", deviceId] });
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [deviceId, qc]);
};

// ESP32 Arduino code generator — supports crop_rover, storage_unit, and esp32_cam
export const generateESP32Code = (device: ESP32Device, supabaseUrl: string, supabaseAnonKey: string) => {
  const apiHelpers = `
bool postJsonToHarvestIQ(const String& body) {
  if (WiFi.status() != WL_CONNECTED) return false;

  WiFiClientSecure client;
  client.setInsecure(); // Required for ESP32 HTTPS with Lovable Cloud

  HTTPClient http;
  String url = String(supabaseUrl) + "/functions/v1/esp32-ingest";
  if (!http.begin(client, url)) {
    Serial.println("HTTP begin failed");
    return false;
  }

  http.addHeader("Content-Type", "application/json");
  http.addHeader("apikey", supabaseKey);
  http.addHeader("Authorization", String("Bearer ") + supabaseKey);
  http.addHeader("x-device-id", deviceId);
  http.addHeader("x-device-key", deviceKey);

  int code = http.POST(body);
  String response = http.getString();
  Serial.printf("Harvest IQ API: %d %s\\n", code, response.c_str());
  http.end();
  return code >= 200 && code < 300;
}

void sendHeartbeat() {
  String body = String("{\"type\":\"heartbeat\",\"ip\":\"") + WiFi.localIP().toString() + "\"}";
  postJsonToHarvestIQ(body);
}`;

  if (device.device_type === "esp32_cam") {
    return `
// ============================================
// ESP32-CAM MJPEG Live Stream for: ${device.device_name}
// Board: AI-Thinker ESP32-CAM with ESP32-CAM-MB baseboard
// Arduino IDE: Board "AI Thinker ESP32-CAM", Partition "Huge APP"
// Generated by Harvest IQ
//
// After flashing, open Serial Monitor (115200) and note the IP shown.
// The web app pulls the live stream from http://<IP>:81/stream
// and registers that IP automatically via the heartbeat call.
// ============================================

#include "esp_camera.h"
#include "esp_http_server.h"
#include "esp_timer.h"
#include "img_converters.h"
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <HTTPClient.h>

const char* ssid     = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";

const char* supabaseUrl = "${supabaseUrl}";
const char* supabaseKey = "${supabaseAnonKey}";
const char* deviceId    = "${device.id}";
const char* deviceKey   = "${device.api_key}";

// AI-Thinker ESP32-CAM pins
#define PWDN_GPIO_NUM 32
#define RESET_GPIO_NUM -1
#define XCLK_GPIO_NUM 0
#define SIOD_GPIO_NUM 26
#define SIOC_GPIO_NUM 27
#define Y9_GPIO_NUM 35
#define Y8_GPIO_NUM 34
#define Y7_GPIO_NUM 39
#define Y6_GPIO_NUM 36
#define Y5_GPIO_NUM 21
#define Y4_GPIO_NUM 19
#define Y3_GPIO_NUM 18
#define Y2_GPIO_NUM 5
#define VSYNC_GPIO_NUM 25
#define HREF_GPIO_NUM 23
#define PCLK_GPIO_NUM 22

#define PART_BOUNDARY "123456789000000000000987654321"
static const char* _STREAM_CONTENT_TYPE = "multipart/x-mixed-replace;boundary=" PART_BOUNDARY;
static const char* _STREAM_BOUNDARY = "\\r\\n--" PART_BOUNDARY "\\r\\n";
static const char* _STREAM_PART = "Content-Type: image/jpeg\\r\\nContent-Length: %u\\r\\n\\r\\n";

httpd_handle_t stream_httpd = NULL;
${apiHelpers}

bool initCamera() {
  camera_config_t config;
  config.ledc_channel = LEDC_CHANNEL_0;
  config.ledc_timer = LEDC_TIMER_0;
  config.pin_d0 = Y2_GPIO_NUM; config.pin_d1 = Y3_GPIO_NUM;
  config.pin_d2 = Y4_GPIO_NUM; config.pin_d3 = Y5_GPIO_NUM;
  config.pin_d4 = Y6_GPIO_NUM; config.pin_d5 = Y7_GPIO_NUM;
  config.pin_d6 = Y8_GPIO_NUM; config.pin_d7 = Y9_GPIO_NUM;
  config.pin_xclk = XCLK_GPIO_NUM; config.pin_pclk = PCLK_GPIO_NUM;
  config.pin_vsync = VSYNC_GPIO_NUM; config.pin_href = HREF_GPIO_NUM;
  config.pin_sscb_sda = SIOD_GPIO_NUM; config.pin_sscb_scl = SIOC_GPIO_NUM;
  config.pin_pwdn = PWDN_GPIO_NUM; config.pin_reset = RESET_GPIO_NUM;
  config.xclk_freq_hz = 20000000;
  config.pixel_format = PIXFORMAT_JPEG;
  if (psramFound()) {
    config.frame_size = FRAMESIZE_VGA;
    config.jpeg_quality = 12;
    config.fb_count = 2;
  } else {
    config.frame_size = FRAMESIZE_QVGA;
    config.jpeg_quality = 14;
    config.fb_count = 1;
  }
  esp_err_t err = esp_camera_init(&config);
  if (err != ESP_OK) { Serial.printf("Camera init failed: 0x%x\\n", err); return false; }
  return true;
}

static esp_err_t stream_handler(httpd_req_t *req) {
  camera_fb_t *fb = NULL;
  esp_err_t res = ESP_OK;
  size_t _jpg_buf_len = 0;
  uint8_t *_jpg_buf = NULL;
  char part_buf[64];
  res = httpd_resp_set_type(req, _STREAM_CONTENT_TYPE);
  if (res != ESP_OK) return res;
  httpd_resp_set_hdr(req, "Access-Control-Allow-Origin", "*");
  while (true) {
    fb = esp_camera_fb_get();
    if (!fb) { res = ESP_FAIL; break; }
    if (fb->format != PIXFORMAT_JPEG) {
      bool jpeg_converted = frame2jpg(fb, 80, &_jpg_buf, &_jpg_buf_len);
      esp_camera_fb_return(fb); fb = NULL;
      if (!jpeg_converted) { res = ESP_FAIL; break; }
    } else {
      _jpg_buf_len = fb->len; _jpg_buf = fb->buf;
    }
    if (res == ESP_OK) res = httpd_resp_send_chunk(req, _STREAM_BOUNDARY, strlen(_STREAM_BOUNDARY));
    if (res == ESP_OK) {
      size_t hlen = snprintf(part_buf, 64, _STREAM_PART, _jpg_buf_len);
      res = httpd_resp_send_chunk(req, part_buf, hlen);
    }
    if (res == ESP_OK) res = httpd_resp_send_chunk(req, (const char *)_jpg_buf, _jpg_buf_len);
    if (fb) { esp_camera_fb_return(fb); fb = NULL; _jpg_buf = NULL; }
    else if (_jpg_buf) { free(_jpg_buf); _jpg_buf = NULL; }
    if (res != ESP_OK) break;
  }
  return res;
}

void startStreamServer() {
  httpd_config_t config = HTTPD_DEFAULT_CONFIG();
  config.server_port = 81;
  config.ctrl_port = 32769;
  httpd_uri_t stream_uri = { .uri = "/stream", .method = HTTP_GET, .handler = stream_handler, .user_ctx = NULL };
  if (httpd_start(&stream_httpd, &config) == ESP_OK) {
    httpd_register_uri_handler(stream_httpd, &stream_uri);
    Serial.println("Stream server started on :81/stream");
  }
}

void setup() {
  Serial.begin(115200);
  WiFi.begin(ssid, password);
  Serial.print("Connecting WiFi");
  while (WiFi.status() != WL_CONNECTED) { delay(500); Serial.print("."); }
  Serial.print("\\nIP: "); Serial.println(WiFi.localIP());
  if (!initCamera()) { Serial.println("Camera FAILED"); }
  startStreamServer();
  sendHeartbeat();
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) { WiFi.reconnect(); delay(3000); return; }
  sendHeartbeat();
  delay(15000); // heartbeat every 15s
}
`.trim();
  }



  if (device.device_type === "crop_rover") {
    return `
// ============================================
// ESP32 CropRover Bot for: ${device.device_name}
// Device Type: crop_rover (ESP32 + L298N)
// Receives HTTP commands and drives motors
// Generated by Harvest IQ
// ============================================

#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <HTTPClient.h>
#include <WebServer.h>

const char* ssid = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";

const char* supabaseUrl = "${supabaseUrl}";
const char* supabaseKey = "${supabaseAnonKey}";
const char* deviceId = "${device.id}";
const char* deviceKey = "${device.api_key}";

// Static IP (edit if your LAN differs)
IPAddress local_IP(192, 168, 1, 90);
IPAddress gateway(192, 168, 1, 1);
IPAddress subnet(255, 255, 255, 0);
IPAddress dns(1, 1, 1, 1);

// L298N motor pins (edit as needed)
static const uint8_t LEFT_IN1 = 12;
static const uint8_t LEFT_IN2 = 13;
static const uint8_t LEFT_ENABLE = 25;

static const uint8_t RIGHT_IN1 = 14;
static const uint8_t RIGHT_IN2 = 27;
static const uint8_t RIGHT_ENABLE = 26;

static const uint8_t LEFT_PWM_CHANNEL = 0;
static const uint8_t RIGHT_PWM_CHANNEL = 1;
static const uint32_t PWM_FREQ = 1000;
static const uint8_t PWM_RESOLUTION = 8;

WebServer server(80);

${apiHelpers}

String readBody() {
  if (!server.hasArg("plain")) return "";
  return server.arg("plain");
}

String extractJsonField(const String& body, const String& key) {
  int keyIndex = body.indexOf(String("\"") + key + "\"");
  if (keyIndex < 0) return "";
  int colon = body.indexOf(':', keyIndex);
  if (colon < 0) return "";
  int start = colon + 1;
  while (start < body.length() && (body[start] == ' ' || body[start] == '"')) start++;
  int end = start;
  while (end < body.length() && body[end] != '"' && body[end] != ',' && body[end] != '}') end++;
  return body.substring(start, end);
}

void setMotor(uint8_t in1, uint8_t in2, uint8_t channel, bool forward, uint8_t speed) {
  if (speed == 0) {
    digitalWrite(in1, LOW);
    digitalWrite(in2, LOW);
    ledcWrite(channel, 0);
    return;
  }
  digitalWrite(in1, forward ? HIGH : LOW);
  digitalWrite(in2, forward ? LOW : HIGH);
  ledcWrite(channel, speed);
}

void moveForward(uint8_t speed) {
  setMotor(LEFT_IN1, LEFT_IN2, LEFT_PWM_CHANNEL, true, speed);
  setMotor(RIGHT_IN1, RIGHT_IN2, RIGHT_PWM_CHANNEL, true, speed);
}

void moveBackward(uint8_t speed) {
  setMotor(LEFT_IN1, LEFT_IN2, LEFT_PWM_CHANNEL, false, speed);
  setMotor(RIGHT_IN1, RIGHT_IN2, RIGHT_PWM_CHANNEL, false, speed);
}

void turnLeft(uint8_t speed) {
  setMotor(LEFT_IN1, LEFT_IN2, LEFT_PWM_CHANNEL, false, speed);
  setMotor(RIGHT_IN1, RIGHT_IN2, RIGHT_PWM_CHANNEL, true, speed);
}

void turnRight(uint8_t speed) {
  setMotor(LEFT_IN1, LEFT_IN2, LEFT_PWM_CHANNEL, true, speed);
  setMotor(RIGHT_IN1, RIGHT_IN2, RIGHT_PWM_CHANNEL, false, speed);
}

void stopMotors() {
  setMotor(LEFT_IN1, LEFT_IN2, LEFT_PWM_CHANNEL, true, 0);
  setMotor(RIGHT_IN1, RIGHT_IN2, RIGHT_PWM_CHANNEL, true, 0);
}

void handleDrive() {
  String body = readBody();
  String direction = extractJsonField(body, "direction");
  String speedStr = extractJsonField(body, "speed");

  if (direction.length() == 0) {
    server.send(400, "application/json", "{\"error\":\"missing direction\"}");
    return;
  }

  int speed = speedStr.toInt();
  speed = constrain(speed, 0, 100);
  uint8_t pwmSpeed = map(speed, 0, 100, 0, 255);

  if (direction == "forward") moveForward(pwmSpeed);
  else if (direction == "backward") moveBackward(pwmSpeed);
  else if (direction == "left") turnLeft(pwmSpeed);
  else if (direction == "right") turnRight(pwmSpeed);
  else if (direction == "stop") stopMotors();
  else stopMotors();

  server.send(200, "application/json", "{\"ok\":true}");
}

void setup() {
  Serial.begin(115200);

  pinMode(LEFT_IN1, OUTPUT);
  pinMode(LEFT_IN2, OUTPUT);
  pinMode(RIGHT_IN1, OUTPUT);
  pinMode(RIGHT_IN2, OUTPUT);

  ledcSetup(LEFT_PWM_CHANNEL, PWM_FREQ, PWM_RESOLUTION);
  ledcSetup(RIGHT_PWM_CHANNEL, PWM_FREQ, PWM_RESOLUTION);
  ledcAttachPin(LEFT_ENABLE, LEFT_PWM_CHANNEL);
  ledcAttachPin(RIGHT_ENABLE, RIGHT_PWM_CHANNEL);

  stopMotors();

  if (!WiFi.config(local_IP, gateway, subnet, dns)) {
    Serial.println("Static IP config failed");
  }
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) { delay(500); Serial.print("."); }
  Serial.print("\nIP: "); Serial.println(WiFi.localIP());

  server.on("/drive", HTTP_POST, handleDrive);
  server.begin();

  sendHeartbeat();
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) { WiFi.reconnect(); delay(1000); }
  server.handleClient();
  sendHeartbeat();
  delay(5000);
}
`.trim();
  }

  if (device.device_type === "storage_unit") {
    return `
// ============================================
// ESP32 Code for: ${device.device_name}
// Device Type: storage_unit
// Sensors: DHT11, MQ135, MFRC522 RFID, LCD 16x2 (I2C)
// Generated by Harvest IQ
// ============================================

#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <HTTPClient.h>
#include <DHT.h>
#include <Wire.h>
#include <LiquidCrystal_I2C.h>
#include <SPI.h>
#include <MFRC522.h>

const char* ssid = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";

const char* supabaseUrl = "${supabaseUrl}";
const char* supabaseKey = "${supabaseAnonKey}";
const char* deviceId = "${device.id}";
const char* deviceKey = "${device.api_key}";

// Pins (ESP32)
#define DHT_PIN 4
#define DHT_TYPE DHT11
#define MQ135_PIN 34
#define RFID_SS_PIN 5
#define RFID_RST_PIN 27

LiquidCrystal_I2C lcd(0x27, 16, 2);
DHT dht(DHT_PIN, DHT_TYPE);
MFRC522 rfid(RFID_SS_PIN, RFID_RST_PIN);

${apiHelpers}

String lastRfid = "----";
unsigned long lastDisplaySwap = 0;
bool displayMode = false;

void showLine(const String& line1, const String& line2) {
  lcd.clear();
  lcd.setCursor(0, 0);
  lcd.print(line1);
  lcd.setCursor(0, 1);
  lcd.print(line2);
}

void sendReadings(float tempC, float humidity, int airRaw) {
  String readings = String("[") +
    "{\"sensor_type\":\"temperature\",\"value\":" + String(tempC, 1) + ",\"unit\":\"C\"}," +
    "{\"sensor_type\":\"humidity\",\"value\":" + String(humidity, 1) + ",\"unit\":\"%\"}," +
    "{\"sensor_type\":\"mq135\",\"value\":" + String(airRaw) + ",\"unit\":\"raw\"}" +
  "]";
  String body = String("{\"type\":\"readings\",\"ip\":\"") + WiFi.localIP().toString() + "\",\"readings\":" + readings + "}";
  postJsonToHarvestIQ(body);
}

void sendRfid(uint32_t uidValue) {
  String readings = String("[") +
    "{\"sensor_type\":\"rfid_uid\",\"value\":" + String(uidValue) + ",\"unit\":\"dec\"}" +
  "]";
  String body = String("{\"type\":\"readings\",\"ip\":\"") + WiFi.localIP().toString() + "\",\"readings\":" + readings + "}";
  postJsonToHarvestIQ(body);
}

uint32_t uidToNumber(MFRC522::Uid *uid) {
  uint32_t value = 0;
  for (byte i = 0; i < uid->size; i++) {
    value = (value << 8) | uid->uidByte[i];
  }
  return value;
}

void setup() {
  Serial.begin(115200);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) { delay(1000); Serial.println("Connecting..."); }
  Serial.print("Connected! IP: "); Serial.println(WiFi.localIP());

  Wire.begin();
  lcd.init();
  lcd.backlight();
  dht.begin();

  SPI.begin();
  rfid.PCD_Init();

  showLine("Storage Unit", "Booting...");
  sendHeartbeat();
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) { WiFi.reconnect(); delay(3000); return; }

  float tempC = dht.readTemperature();
  float humidity = dht.readHumidity();
  int airRaw = analogRead(MQ135_PIN);

  if (!isnan(tempC) && !isnan(humidity)) {
    sendReadings(tempC, humidity, airRaw);
  }

  if (rfid.PICC_IsNewCardPresent() && rfid.PICC_ReadCardSerial()) {
    uint32_t uidValue = uidToNumber(&rfid.uid);
    lastRfid = String(uidValue);
    sendRfid(uidValue);
    rfid.PICC_HaltA();
    rfid.PCD_StopCrypto1();
  }

  unsigned long now = millis();
  if (now - lastDisplaySwap > 2000) {
    displayMode = !displayMode;
    lastDisplaySwap = now;
  }

  if (displayMode) {
    String l1 = String("T:") + String(tempC, 1) + "C H:" + String(humidity, 0) + "%";
    String l2 = String("Air:") + String(airRaw) + " RFID:" + lastRfid;
    showLine(l1, l2);
  } else {
    showLine("Storage OK", "Last RFID:" + lastRfid);
  }

  sendHeartbeat();
  delay(30000);
}
`.trim();
  }

  if (device.device_type === "uno_r4_storage") {
    return `
// ============================================
// Arduino UNO R4 WiFi Storage Unit: ${device.device_name}
// Device Type: uno_r4_storage
// Sensors: DHT22, MQ135, RC522 RFID, MLX90614, 16x4 I2C LCD
// Relays: 4-channel module
// Generated by Harvest IQ
// ============================================

#include <WiFiS3.h>
#include <ArduinoHttpClient.h>
#include <DHT.h>
#include <Wire.h>
#include <LiquidCrystal_I2C.h>
#include <SPI.h>
#include <MFRC522.h>
#include <Adafruit_MLX90614.h>

const char* ssid = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";

const char* supabaseUrl = "${supabaseUrl}";
const char* supabaseKey = "${supabaseAnonKey}";
const char* deviceId = "${device.id}";
const char* deviceKey = "${device.api_key}";

// MQ135
static const uint8_t MQ135_A0 = A0;
static const uint8_t MQ135_DOUT = 2;

// DHT22
static const uint8_t DHT_PIN = 3;
static const uint8_t DHT_TYPE = DHT22;

// I2C LCD + MLX90614
static const uint8_t I2C_SDA = A4;
static const uint8_t I2C_SCL = A5;
static const uint8_t LCD_ADDR = 0x27;

// RC522 RFID (SPI)
static const uint8_t RFID_SS = 10;
static const uint8_t RFID_RST = 9;

// Relays
static const uint8_t RELAY_1 = 8;
static const uint8_t RELAY_2 = 7;
static const uint8_t RELAY_3 = 6;
static const uint8_t RELAY_4 = 5;

LiquidCrystal_I2C lcd(LCD_ADDR, 16, 4);
DHT dht(DHT_PIN, DHT_TYPE);
MFRC522 rfid(RFID_SS, RFID_RST);
Adafruit_MLX90614 mlx = Adafruit_MLX90614();

String lastRfid = "----";
unsigned long lastDisplaySwap = 0;
bool displayMode = false;

String getHostFromUrl(const String& url) {
  int start = url.indexOf("://");
  start = (start < 0) ? 0 : start + 3;
  int end = url.indexOf('/', start);
  if (end < 0) end = url.length();
  return url.substring(start, end);
}

bool postJsonToHarvestIQ(const String& body) {
  if (WiFi.status() != WL_CONNECTED) return false;

  String host = getHostFromUrl(String(supabaseUrl));
  WiFiSSLClient wifi;
  HttpClient http(wifi, host.c_str(), 443);

  http.beginRequest();
  http.post("/functions/v1/esp32-ingest");
  http.sendHeader("Content-Type", "application/json");
  http.sendHeader("apikey", supabaseKey);
  http.sendHeader("Authorization", String("Bearer ") + supabaseKey);
  http.sendHeader("x-device-id", deviceId);
  http.sendHeader("x-device-key", deviceKey);
  http.sendHeader("Content-Length", body.length());
  http.beginBody();
  http.print(body);
  http.endRequest();

  int status = http.responseStatusCode();
  String response = http.responseBody();
  Serial.print("Harvest IQ API: ");
  Serial.print(status);
  Serial.print(" ");
  Serial.println(response);
  http.stop();

  return status >= 200 && status < 300;
}

void sendHeartbeat() {
  String body = String("{\"type\":\"heartbeat\",\"ip\":\"") + WiFi.localIP().toString() + "\"}";
  postJsonToHarvestIQ(body);
}

void sendReadings(float tempC, float humidity, float irTempC, int airRaw, int airDout) {
  String readings = String("[") +
    "{\"sensor_type\":\"temperature\",\"value\":" + String(tempC, 1) + ",\"unit\":\"C\"}," +
    "{\"sensor_type\":\"humidity\",\"value\":" + String(humidity, 1) + ",\"unit\":\"%\"}," +
    "{\"sensor_type\":\"ir_temp\",\"value\":" + String(irTempC, 1) + ",\"unit\":\"C\"}," +
    "{\"sensor_type\":\"mq135\",\"value\":" + String(airRaw) + ",\"unit\":\"raw\"}," +
    "{\"sensor_type\":\"mq135_dout\",\"value\":" + String(airDout) + ",\"unit\":\"level\"}" +
  "]";
  String body = String("{\"type\":\"readings\",\"ip\":\"") + WiFi.localIP().toString() + "\",\"readings\":" + readings + "}";
  postJsonToHarvestIQ(body);
}

void sendRfid(uint32_t uidValue) {
  String readings = String("[") +
    "{\"sensor_type\":\"rfid_uid\",\"value\":" + String(uidValue) + ",\"unit\":\"dec\"}" +
  "]";
  String body = String("{\"type\":\"readings\",\"ip\":\"") + WiFi.localIP().toString() + "\",\"readings\":" + readings + "}";
  postJsonToHarvestIQ(body);
}

uint32_t uidToNumber(MFRC522::Uid* uid) {
  uint32_t value = 0;
  for (byte i = 0; i < uid->size; i++) {
    value = (value << 8) | uid->uidByte[i];
  }
  return value;
}

void showLine(const String& l1, const String& l2, const String& l3, const String& l4) {
  lcd.clear();
  lcd.setCursor(0, 0); lcd.print(l1);
  lcd.setCursor(0, 1); lcd.print(l2);
  lcd.setCursor(0, 2); lcd.print(l3);
  lcd.setCursor(0, 3); lcd.print(l4);
}

void setup() {
  Serial.begin(115200);

  pinMode(MQ135_DOUT, INPUT);
  pinMode(RELAY_1, OUTPUT);
  pinMode(RELAY_2, OUTPUT);
  pinMode(RELAY_3, OUTPUT);
  pinMode(RELAY_4, OUTPUT);

  digitalWrite(RELAY_1, LOW);
  digitalWrite(RELAY_2, LOW);
  digitalWrite(RELAY_3, LOW);
  digitalWrite(RELAY_4, LOW);

  Wire.begin();
  lcd.init();
  lcd.backlight();
  dht.begin();
  mlx.begin();
  SPI.begin();
  rfid.PCD_Init();

  lcd.setCursor(0, 0);
  lcd.print("Storage Unit");
  lcd.setCursor(0, 1);
  lcd.print("Connecting...");

  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.print("\nIP: ");
  Serial.println(WiFi.localIP());

  sendHeartbeat();
}

void setFansForTemp(float tempC) {
  if (isnan(tempC)) return;

  bool fansOn = tempC >= 24.0 && tempC < 30.0;
  digitalWrite(RELAY_1, fansOn ? HIGH : LOW);
  digitalWrite(RELAY_2, fansOn ? HIGH : LOW);
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) {
    WiFi.reconnect();
    delay(2000);
    return;
  }

  float tempC = dht.readTemperature();
  float humidity = dht.readHumidity();
  float irTemp = mlx.readObjectTempC();
  int airRaw = analogRead(MQ135_A0);
  int airDout = digitalRead(MQ135_DOUT);

  setFansForTemp(tempC);

  if (!isnan(tempC) && !isnan(humidity)) {
    sendReadings(tempC, humidity, irTemp, airRaw, airDout);
  }

  if (rfid.PICC_IsNewCardPresent() && rfid.PICC_ReadCardSerial()) {
    uint32_t uidValue = uidToNumber(&rfid.uid);
    lastRfid = String(uidValue);
    sendRfid(uidValue);
    rfid.PICC_HaltA();
    rfid.PCD_StopCrypto1();
  }

  unsigned long now = millis();
  if (now - lastDisplaySwap > 2000) {
    displayMode = !displayMode;
    lastDisplaySwap = now;
  }

  if (displayMode) {
    String l1 = String("T:") + String(tempC, 1) + "C H:" + String(humidity, 0) + "%";
    String l2 = String("IR:") + String(irTemp, 1) + "C";
    String l3 = String("Air:") + String(airRaw) + " D:" + String(airDout);
    String l4 = String("RFID:") + lastRfid;
    showLine(l1, l2, l3, l4);
  } else {
    showLine("Storage OK", "Last RFID:", lastRfid, "WiFi:" + WiFi.localIP().toString());
  }

  sendHeartbeat();
  delay(30000);
}
`.trim();
  }

  return `
// ============================================
// ESP32 Code for: ${device.device_name}
// Device Type: ${device.device_type}
// Generated by Harvest IQ
// ============================================

#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <HTTPClient.h>

const char* ssid = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";

const char* supabaseUrl = "${supabaseUrl}";
const char* supabaseKey = "${supabaseAnonKey}";
const char* deviceId = "${device.id}";
const char* deviceKey = "${device.api_key}";

${device.device_type === "crop_rover" ? `#define SOIL_MOISTURE_PIN 34
#define LIGHT_SENSOR_PIN 35
#define PH_SENSOR_PIN 32` : `#define TEMP_SENSOR_PIN 34
#define HUMIDITY_SENSOR_PIN 35
#define WEIGHT_SENSOR_PIN 32`}
${apiHelpers}

float percentFromAnalog(int pin) {
  return constrain((analogRead(pin) / 4095.0) * 100.0, 0.0, 100.0);
}

void sendReadings(const String& readingsJson) {
  String body = String("{\"type\":\"readings\",\"ip\":\"") + WiFi.localIP().toString() + "\",\"readings\":" + readingsJson + "}";
  postJsonToHarvestIQ(body);
}

void setup() {
  Serial.begin(115200);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) { delay(1000); Serial.println("Connecting..."); }
  Serial.print("Connected! IP: "); Serial.println(WiFi.localIP());
  sendHeartbeat();
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) { WiFi.reconnect(); delay(3000); return; }
  sendHeartbeat();
${device.device_type === "crop_rover" ? `  float soilMoisture = percentFromAnalog(SOIL_MOISTURE_PIN);
  float lightIntensity = analogRead(LIGHT_SENSOR_PIN) / 4.095;
  float soilPH = (analogRead(PH_SENSOR_PIN) / 4095.0) * 14.0;
  String readings = String("[") +
    "{\"sensor_type\":\"soil_moisture\",\"value\":" + String(soilMoisture, 2) + ",\"unit\":\"%\"}," +
    "{\"sensor_type\":\"light_intensity\",\"value\":" + String(lightIntensity, 2) + ",\"unit\":\"lux\"}," +
    "{\"sensor_type\":\"soil_ph\",\"value\":" + String(soilPH, 2) + ",\"unit\":\"pH\"}" +
  "]";
  sendReadings(readings);` : `  float temperature = percentFromAnalog(TEMP_SENSOR_PIN) * 0.6;
  float humidity = percentFromAnalog(HUMIDITY_SENSOR_PIN);
  float weight = analogRead(WEIGHT_SENSOR_PIN) / 4.095;
  String readings = String("[") +
    "{\"sensor_type\":\"temperature\",\"value\":" + String(temperature, 2) + ",\"unit\":\"C\"}," +
    "{\"sensor_type\":\"humidity\",\"value\":" + String(humidity, 2) + ",\"unit\":\"%\"}," +
    "{\"sensor_type\":\"weight\",\"value\":" + String(weight, 2) + ",\"unit\":\"kg\"}" +
  "]";
  sendReadings(readings);`}
  delay(30000);
}
`.trim();
};
