import { useState, useEffect, useCallback } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

export type ESP32Device = {
  id: string;
  user_id: string;
  device_name: string;
  device_type: string;
  ip_address: string | null;
  api_key: string;
  is_online: boolean;
  last_seen: string | null;
  created_at: string;
};

export type SensorReading = {
  id: string;
  device_id: string;
  sensor_type: string;
  value: number;
  unit: string;
  created_at: string;
};

export const useDevices = () => {
  const { user } = useAuth();
  return useQuery({
    queryKey: ["esp32_devices", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("esp32_devices")
        .select("*")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data as ESP32Device[];
    },
    enabled: !!user,
  });
};

export const useAddDevice = () => {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (device: { device_name: string; device_type: string; ip_address?: string }) => {
      const { data, error } = await supabase
        .from("esp32_devices")
        .insert({ ...device, user_id: user!.id })
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["esp32_devices"] });
      toast.success("Device added");
    },
    onError: (e) => toast.error(e.message),
  });
};

export const useDeleteDevice = () => {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from("esp32_devices").delete().eq("id", id);
      if (error) throw error;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["esp32_devices"] });
      toast.success("Device removed");
    },
    onError: (e) => toast.error(e.message),
  });
};

export const useSensorReadings = (deviceId?: string) => {
  return useQuery({
    queryKey: ["sensor_readings", deviceId],
    queryFn: async () => {
      let query = supabase
        .from("esp32_sensor_readings")
        .select("*")
        .order("created_at", { ascending: false })
        .limit(100);
      if (deviceId) query = query.eq("device_id", deviceId);
      const { data, error } = await query;
      if (error) throw error;
      return data as SensorReading[];
    },
    enabled: !!deviceId,
    refetchInterval: 5000,
  });
};

export const useRealtimeSensorReadings = (deviceId?: string) => {
  const qc = useQueryClient();

  useEffect(() => {
    if (!deviceId) return;

    const channel = supabase
      .channel(`sensor-${deviceId}`)
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table: "esp32_sensor_readings",
          filter: `device_id=eq.${deviceId}`,
        },
        () => {
          qc.invalidateQueries({ queryKey: ["sensor_readings", deviceId] });
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [deviceId, qc]);
};

// ESP32 Arduino code generator — supports crop_rover, storage_unit, and esp32_cam
export const generateESP32Code = (device: ESP32Device, supabaseUrl: string, supabaseAnonKey: string) => {
  const apiHelpers = `
bool postJsonToHarvestIQ(const String& body) {
  if (WiFi.status() != WL_CONNECTED) return false;

  WiFiClientSecure client;
  client.setInsecure(); // Required for ESP32 HTTPS with Lovable Cloud

  HTTPClient http;
  String url = String(supabaseUrl) + "/functions/v1/esp32-ingest";
  if (!http.begin(client, url)) {
    Serial.println("HTTP begin failed");
    return false;
  }

  http.addHeader("Content-Type", "application/json");
  http.addHeader("apikey", supabaseKey);
  http.addHeader("Authorization", String("Bearer ") + supabaseKey);
  http.addHeader("x-device-id", deviceId);
  http.addHeader("x-device-key", deviceKey);

  int code = http.POST(body);
  String response = http.getString();
  Serial.printf("Harvest IQ API: %d %s\\n", code, response.c_str());
  http.end();
  return code >= 200 && code < 300;
}

void sendHeartbeat() {
  String body = String("{\"type\":\"heartbeat\",\"ip\":\"") + WiFi.localIP().toString() + "\"}";
  postJsonToHarvestIQ(body);
}`;

  if (device.device_type === "esp32_cam") {
    return `
// ============================================
// ESP32-CAM Code for: ${device.device_name}
// Board: AI-Thinker ESP32-CAM with ESP32-CAM-MB baseboard
// Arduino IDE: Board "AI Thinker ESP32-CAM", Partition "Huge APP"
// Generated by Harvest IQ
// ============================================

#include "esp_camera.h"
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <HTTPClient.h>

const char* ssid     = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";

const char* supabaseUrl = "${supabaseUrl}";
const char* supabaseKey = "${supabaseAnonKey}";
const char* deviceId    = "${device.id}";
const char* deviceKey   = "${device.api_key}";
const char* fieldLabel  = "Field A - Section 1";

// AI-Thinker ESP32-CAM pins
#define PWDN_GPIO_NUM 32
#define RESET_GPIO_NUM -1
#define XCLK_GPIO_NUM 0
#define SIOD_GPIO_NUM 26
#define SIOC_GPIO_NUM 27
#define Y9_GPIO_NUM 35
#define Y8_GPIO_NUM 34
#define Y7_GPIO_NUM 39
#define Y6_GPIO_NUM 36
#define Y5_GPIO_NUM 21
#define Y4_GPIO_NUM 19
#define Y3_GPIO_NUM 18
#define Y2_GPIO_NUM 5
#define VSYNC_GPIO_NUM 25
#define HREF_GPIO_NUM 23
#define PCLK_GPIO_NUM 22
${apiHelpers}

bool initCamera() {
  camera_config_t config;
  config.ledc_channel = LEDC_CHANNEL_0;
  config.ledc_timer = LEDC_TIMER_0;
  config.pin_d0 = Y2_GPIO_NUM; config.pin_d1 = Y3_GPIO_NUM;
  config.pin_d2 = Y4_GPIO_NUM; config.pin_d3 = Y5_GPIO_NUM;
  config.pin_d4 = Y6_GPIO_NUM; config.pin_d5 = Y7_GPIO_NUM;
  config.pin_d6 = Y8_GPIO_NUM; config.pin_d7 = Y9_GPIO_NUM;
  config.pin_xclk = XCLK_GPIO_NUM; config.pin_pclk = PCLK_GPIO_NUM;
  config.pin_vsync = VSYNC_GPIO_NUM; config.pin_href = HREF_GPIO_NUM;
  config.pin_sscb_sda = SIOD_GPIO_NUM; config.pin_sscb_scl = SIOC_GPIO_NUM;
  config.pin_pwdn = PWDN_GPIO_NUM; config.pin_reset = RESET_GPIO_NUM;
  config.xclk_freq_hz = 20000000;
  config.pixel_format = PIXFORMAT_JPEG;

  if (psramFound()) {
    config.frame_size = FRAMESIZE_SVGA;
    config.jpeg_quality = 10;
    config.fb_count = 2;
  } else {
    config.frame_size = FRAMESIZE_VGA;
    config.jpeg_quality = 12;
    config.fb_count = 1;
  }

  esp_err_t err = esp_camera_init(&config);
  if (err != ESP_OK) {
    Serial.printf("Camera init failed: 0x%x\\n", err);
    return false;
  }
  return true;
}

void uploadImage(camera_fb_t* fb) {
  if (WiFi.status() != WL_CONNECTED) return;

  WiFiClientSecure client;
  client.setInsecure();

  HTTPClient http;
  String url = String(supabaseUrl) + "/functions/v1/esp32-ingest";
  if (!http.begin(client, url)) {
    Serial.println("HTTP begin failed");
    return;
  }

  http.addHeader("Content-Type", "image/jpeg");
  http.addHeader("apikey", supabaseKey);
  http.addHeader("Authorization", String("Bearer ") + supabaseKey);
  http.addHeader("x-device-id", deviceId);
  http.addHeader("x-device-key", deviceKey);
  http.addHeader("x-location", fieldLabel);

  int code = http.POST(fb->buf, fb->len);
  String response = http.getString();
  Serial.printf("Camera upload + AI: %d %s\\n", code, response.c_str());
  http.end();
}

void setup() {
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  WiFi.begin(ssid, password);
  Serial.print("Connecting to WiFi");
  while (WiFi.status() != WL_CONNECTED) { delay(500); Serial.print("."); }
  Serial.println();
  Serial.print("WiFi connected. IP: "); Serial.println(WiFi.localIP());
  sendHeartbeat();
  if (!initCamera()) { Serial.println("Camera init FAILED — check baseboard/ribbon cable and board selection"); }
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) {
    WiFi.reconnect();
    delay(3000);
    return;
  }
  sendHeartbeat();
  camera_fb_t* fb = esp_camera_fb_get();
  if (!fb) { Serial.println("Capture failed"); delay(2000); return; }
  uploadImage(fb);
  esp_camera_fb_return(fb);
  delay(60000); // capture every 60s
}
`.trim();
  }

  return `
// ============================================
// ESP32 Code for: ${device.device_name}
// Device Type: ${device.device_type}
// Generated by Harvest IQ
// ============================================

#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <HTTPClient.h>

const char* ssid = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";

const char* supabaseUrl = "${supabaseUrl}";
const char* supabaseKey = "${supabaseAnonKey}";
const char* deviceId = "${device.id}";
const char* deviceKey = "${device.api_key}";

${device.device_type === "crop_rover" ? `#define SOIL_MOISTURE_PIN 34
#define LIGHT_SENSOR_PIN 35
#define PH_SENSOR_PIN 32` : `#define TEMP_SENSOR_PIN 34
#define HUMIDITY_SENSOR_PIN 35
#define WEIGHT_SENSOR_PIN 32`}
${apiHelpers}

float percentFromAnalog(int pin) {
  return constrain((analogRead(pin) / 4095.0) * 100.0, 0.0, 100.0);
}

void sendReadings(const String& readingsJson) {
  String body = String("{\"type\":\"readings\",\"ip\":\"") + WiFi.localIP().toString() + "\",\"readings\":" + readingsJson + "}";
  postJsonToHarvestIQ(body);
}

void setup() {
  Serial.begin(115200);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) { delay(1000); Serial.println("Connecting..."); }
  Serial.print("Connected! IP: "); Serial.println(WiFi.localIP());
  sendHeartbeat();
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) { WiFi.reconnect(); delay(3000); return; }
  sendHeartbeat();
${device.device_type === "crop_rover" ? `  float soilMoisture = percentFromAnalog(SOIL_MOISTURE_PIN);
  float lightIntensity = analogRead(LIGHT_SENSOR_PIN) / 4.095;
  float soilPH = (analogRead(PH_SENSOR_PIN) / 4095.0) * 14.0;
  String readings = String("[") +
    "{\"sensor_type\":\"soil_moisture\",\"value\":" + String(soilMoisture, 2) + ",\"unit\":\"%\"}," +
    "{\"sensor_type\":\"light_intensity\",\"value\":" + String(lightIntensity, 2) + ",\"unit\":\"lux\"}," +
    "{\"sensor_type\":\"soil_ph\",\"value\":" + String(soilPH, 2) + ",\"unit\":\"pH\"}" +
  "]";
  sendReadings(readings);` : `  float temperature = percentFromAnalog(TEMP_SENSOR_PIN) * 0.6;
  float humidity = percentFromAnalog(HUMIDITY_SENSOR_PIN);
  float weight = analogRead(WEIGHT_SENSOR_PIN) / 4.095;
  String readings = String("[") +
    "{\"sensor_type\":\"temperature\",\"value\":" + String(temperature, 2) + ",\"unit\":\"C\"}," +
    "{\"sensor_type\":\"humidity\",\"value\":" + String(humidity, 2) + ",\"unit\":\"%\"}," +
    "{\"sensor_type\":\"weight\",\"value\":" + String(weight, 2) + ",\"unit\":\"kg\"}" +
  "]";
  sendReadings(readings);`}
  delay(30000);
}
`.trim();
};
